/* Full hazwoper-osha.com course catalog, pulled from their live /api/get_category_courses/{id}
   endpoint on 2026-08-17. Every course here links out to hazwoper-osha.com — this site does not
   sell or host courses. Re-verify against the live site if this list is reused long-term. */
window.HOC_CATALOG = {
  baseUrl: "https://hazwoper-osha.com/",
  categories: [
    { name: "HAZWOPER Training (29 CFR 1910.120)", courses: [
      { t: "OSHA 40 Hour HAZWOPER Training", u: "online-courses/osha-40-hour-hazwoper-online" },
      { t: "OSHA 24 Hour HAZWOPER Training", u: "online-courses/osha-24-hour-hazwoper-online" },
      { t: "OSHA 8 Hour HAZWOPER Refresher Training", u: "online-courses/osha-8-hour-hazwoper-refresher-online" },
      { t: "OSHA 8 Hour HAZWOPER Supervisor Training", u: "online-courses/osha-8-hour-hazwoper-supervisor-online-training" },
      { t: "OSHA 8 Hour HAZWOPER Supervisor Refresher Training", u: "online-courses/osha-8-hour-hazwoper-supervisor-training-refresher" },
      { t: "OSHA 8-Hour HAZWOPER and Safe Ammonia Handling Refresher Training", u: "online-courses/osha-8-hour-hazwoper-and-safe-ammonia-handling-refresher-training" },
      { t: "OSHA HAZWOPER and RCRA Hazardous Waste Management Technician Safety Training", u: "online-courses/osha-hazwoper-and-rcra-hazardous-waste-management-technician-safety-training" },
      { t: "Cal/OSHA 40 Hour HAZWOPER Training", u: "online-courses/cal40-new" },
      { t: "Cal/OSHA 24-Hour HAZWOPER Training", u: "online-courses/cal-osha-24-hour-hazwoper-training" },
      { t: "Cal/OSHA 8-Hour HAZWOPER Refresher Training", u: "online-courses/cal-osha-8-hour-hazwoper-refresher-training" },
      { t: "Cal/OSHA Spill Prevention and Response Safety Training", u: "online-courses/cal-osha-spill-prevention-and-response-safety-training" },
      { t: "OSHA 24 Hour HAZWOPER - RCRA TSD Operations Training", u: "online-courses/24-hour-hazwoper-tsd-operations-p" },
      { t: "OSHA 8 Hour HAZWOPER Annual Refresher - RCRA TSD Operations Training", u: "online-courses/8-hour-hazwoper-tsd-operations-p" },
      { t: "OSHA 8 Hour HAZWOPER (q) Incident Command Training", u: "online-courses/8-hour-hazwoper-incident-command-training" }
    ]},
    { name: "Incident Command System", courses: [
      { t: "Introduction to the Incident Command System (ICS 100) Training", u: "online-courses/introduction-to-the-incident-command-system-ics-100-training" },
      { t: "Basic Incident Command System for Initial Response (ICS 200) Training", u: "online-courses/basic-incident-command-system-for-initial-response-ics-200-training" }
    ]},
    { name: "OSHA 10 & 30 Hour Outreach Training", courses: [
      { t: "OSHA 10-Hour Outreach Training for Construction Industry with DOL Card", u: "online-courses/osha-10-hour-outreach-training-for-construction-industry" },
      { t: "OSHA 30-Hour Outreach Training for Construction Industry with DOL Card (English)", u: "online-courses/osha-30-hour-outreach-training-for-construction-industry-with-dol-card-en" },
      { t: "OSHA 30-Hour Outreach Training for Construction Industry with DOL Card (Spanish)", u: "online-courses/osha-30-hour-outreach-training-for-construction-industry-spanish" },
      { t: "OSHA 10-Hour General Industry Outreach Training with DOL Card", u: "online-courses/osha-10-hour-general-industry-outreach-training" }
    ]},
    { name: "OSHA Construction Safety Training", courses: [
      { t: "OSHA Competent Person for Excavation, Trenching, and Shoring Training", u: "online-courses/competent-person-for-excavation-trenching-and-shoring" },
      { t: "OSHA Excavation, Trenching, and Shoring Safety Training", u: "online-courses/osha-excavation-trenching-and-shoring-safety-training" },
      { t: "OSHA Confined Space Awareness Training", u: "online-courses/confined-space-awareness-training-for-construction-industry" },
      { t: "OSHA Competent Person for Confined Spaces Training", u: "online-courses/osha-competent-person-for-confined-spaces-training" },
      { t: "OSHA Permit Required Confined Space Entry Training", u: "online-courses/osha-permit-required-confined-space-entry-training" },
      { t: "OSHA Confined Space Supervisor Training", u: "online-courses/osha-confined-space-supervisor-training" },
      { t: "OSHA Competent Person for Silica Training", u: "online-courses/osha-competent-person-for-silica-training-new" },
      { t: "OSHA Silica Awareness Training", u: "online-courses/osha-silica-awareness-online-training" },
      { t: "OSHA Lead Awareness Training", u: "online-courses/lead-awareness-training-for-construction-industry" },
      { t: "OSHA Asbestos Awareness Training", u: "online-courses/asbestos-awareness-training" },
      { t: "OSHA Benzene Awareness Training", u: "online-courses/osha-benzene-awareness-training" },
      { t: "OSHA Hexavalent Chromium Awareness Training", u: "online-courses/osha-hexavalent-chromium-awareness-training" },
      { t: "OSHA Hexavalent Chromium Safety and Remediation Training", u: "online-courses/osha-hexavalent-chromium-safety-and-remediation-training" },
      { t: "OSHA Cadmium Awareness Training", u: "online-courses/osha-cadmium-awareness-training" },
      { t: "Dust Disturbance and Mitigation Awareness Training", u: "online-courses/dust-disturbance-and-mitigation-awareness-training" },
      { t: "OSHA Aerial - Scissor and Boom Lift Safety Training", u: "online-courses/aerial-scissor-lift-training" },
      { t: "OSHA Scaffolding Safety Training", u: "online-courses/scaffolding-safety-training" },
      { t: "OSHA Scaffolding Erection and Inspection Training for Competent Person", u: "online-courses/osha-scaffolding-erection-and-inspection-training-for-competent-person" },
      { t: "OSHA Competent Person for Swing Stage (Suspended) Scaffold Training", u: "online-courses/osha-competent-person-for-swing-stage-suspended-scaffold-training" },
      { t: "OSHA Qualified Person for Scaffolding Safety Training", u: "online-courses/osha-qualified-person-for-scaffolding-safety-training" },
      { t: "OSHA Ladder and Stairway Safety Training", u: "online-courses/osha-ladder-and-stairway-safety-training" },
      { t: "OSHA Fall Protection Safety Training", u: "online-courses/osha-fall-protection-safety-training" },
      { t: "OSHA Competent Person for Fall Protection Training", u: "online-courses/osha-competent-person-for-fall-protection-training-new" },
      { t: "OSHA Motorized Mobile Platforms Safety Awareness Training", u: "online-courses/osha-motorized-mobile-platforms-safety-awareness-training" },
      { t: "Rigging Safety Awareness Training", u: "online-courses/rigging-safety-awareness-training" },
      { t: "OSHA Powered Mobile Equipment Safety Training", u: "online-courses/osha-powered-mobile-equipment-safety-training" },
      { t: "OSHA Forklift Safety Training", u: "online-courses/forklift-safety-training" },
      { t: "Pallet Jack (Manual, Electric) Online Training", u: "online-courses/osha-pallet-jack-safety-training" },
      { t: "OSHA Spill Prevention and Response Safety Training", u: "online-courses/osha-spill-prevention-and-response-safety-training" },
      { t: "Cal/OSHA Spill Prevention and Response Safety Training", u: "online-courses/cal-osha-spill-prevention-and-response-safety-training" },
      { t: "OSHA Compressed Gas Cylinder Safety Training", u: "online-courses/osha-compressed-gas-cylinder-safety-training" },
      { t: "OSHA Hand and Power Tools Safety Training", u: "online-courses/osha-hand-and-power-tools-safety-training-new" },
      { t: "Motor Vehicles and Mechanized Equipment Training for Construction", u: "online-courses/motor-vehicles-and-mechanized-equipment-training-for-construction" },
      { t: "OSHA Driving Safety Training", u: "online-courses/osha-driving-safety-training" },
      { t: "National Flagger and Traffic Control for Construction Sites Certification Training", u: "online-courses/national-flagger-and-traffic-control-for-construction-sites-certification-training" },
      { t: "OSHA Workzone Traffic Control Awareness Training", u: "online-courses/osha-workzone-traffic-control-awareness-training" },
      { t: "OSHA Steel Erection Safety Training", u: "online-courses/osha-steel-erection-safety-training" },
      { t: "OSHA Welding, Cutting, and Brazing for Construction Training", u: "online-courses/welding-cutting-and-brazing-for-construction" },
      { t: "OSHA Concrete and Masonry Awareness Training", u: "online-courses/osha-concrete-and-masonry-awareness-training" },
      { t: "OSHA Hot Work Safety for Construction Training", u: "online-courses/osha-hot-work-safety-for-construction-training" },
      { t: "Cal Wildfire Smoke Safety and Emergency Training", u: "online-courses/cal-wildfire-smoke-safety-and-emergency-training" },
      { t: "Wildfire Smoke Safety Awareness Training", u: "online-courses/wildfire-smoke-safety-awareness-training" },
      { t: "Cal/OSHA Heat Illness Prevention Training for Construction", u: "online-courses/cal-osha-heat-illness-prevention-training-for-construction" },
      { t: "OSHA Cold Stress Awareness Training", u: "online-courses/osha-cold-stress-awareness-training" },
      { t: "General Safety and Health Training for Construction", u: "online-courses/general-safety-and-health-training-for-construction" },
      { t: "First Aid, CPR, and AED Safety Training", u: "online-courses/first-aid-cpr-and-aed-safety-awareness-training" },
      { t: "OSHA Noise Exposure and Hearing Conservation Training", u: "online-courses/osha-noise-exposure-and-hearing-conservation-training" },
      { t: "Drug and Alcohol Abuse Prevention Training for Construction Workers", u: "online-courses/drug-and-alcohol-abuse-prevention-training-for-construction-workers" },
      { t: "OSHA SCBA Awareness and Safe Use Training", u: "online-courses/osha-scba-awareness-and-safe-use-training" },
      { t: "OSHA Personal Protective Equipment (PPE) Training", u: "online-courses/osha-personal-protective-equipment-training" },
      { t: "OSHA Full Body Harness Training", u: "online-courses/osha-full-body-harness-training" },
      { t: "OSHA Workplace Violence Prevention Training", u: "online-courses/osha-workplace-violence-prevention-training" }
    ]},
    { name: "OSHA General Industry Safety Training", courses: [
      { t: "First Aid, CPR, and AED Safety Training", u: "online-courses/first-aid-cpr-and-aed-safety-awareness-training" },
      { t: "OSHA Bloodborne Pathogens Training", u: "online-courses/bloodborne-pathogens-training" },
      { t: "OSHA Warehouse Safety Training", u: "online-courses/osha-warehouse-safety-training" },
      { t: "OSHA Fire Safety Training", u: "online-courses/fire-safety-training" },
      { t: "Authorized Gas Tester Training", u: "online-courses/authorized-gas-tester-training" },
      { t: "OSHA Compressed Gas Cylinder Safety Training", u: "online-courses/osha-compressed-gas-cylinder-safety-training" },
      { t: "OSHA Lockout Tagout (LOTO) Training", u: "online-courses/osha-lockout-tagout-loto-training" },
      { t: "OSHA ANSI Lockout Tagout LOTO Certificate Training", u: "online-courses/osha-ansi-lockout-tagout-loto-certificate-training" },
      { t: "OSHA Machine Guarding Safety Training", u: "online-courses/osha-machine-guarding-safety-training-new" },
      { t: "OSHA Emergency Action Plans Training", u: "online-courses/osha-emergency-action-plan-training" },
      { t: "OSHA 300 Recordkeeping and Reporting Training", u: "online-courses/osha-300-recordkeeping-and-reporting-training" },
      { t: "OSHA Incident Investigation Training", u: "online-courses/osha-incident-investigation-training-new" },
      { t: "OSHA Job Hazard Analysis Training", u: "online-courses/osha-job-hazard-analysis-training" },
      { t: "OSHA Workplace Violence Prevention Training", u: "online-courses/osha-workplace-violence-prevention-training" },
      { t: "Radiofrequency (RF) Safety and Hazard Awareness Training", u: "online-courses/radiofrequency-rf-safety-and-hazard-awareness-training" },
      { t: "OSHA Process Safety Management Training", u: "online-courses/osha-process-safety-management-training" },
      { t: "OSHA Permit Required Confined Space Entry Training", u: "online-courses/osha-permit-required-confined-space-entry-training" },
      { t: "OSHA Confined Space Supervisor Training", u: "online-courses/osha-confined-space-supervisor-training" },
      { t: "OSHA Aerial - Scissor and Boom Lift Safety Training", u: "online-courses/aerial-scissor-lift-training" },
      { t: "OSHA Scaffolding Safety Training", u: "online-courses/scaffolding-safety-training" },
      { t: "OSHA Powered Mobile Equipment Safety Training", u: "online-courses/osha-powered-mobile-equipment-safety-training" },
      { t: "OSHA Forklift Safety Training", u: "online-courses/forklift-safety-training" },
      { t: "Pallet Jack (Manual, Electric) Online Training", u: "online-courses/osha-pallet-jack-safety-training" },
      { t: "OSHA Motorized Mobile Platforms Safety Awareness Training", u: "online-courses/osha-motorized-mobile-platforms-safety-awareness-training" },
      { t: "OSHA Workzone Traffic Control Awareness Training", u: "online-courses/osha-workzone-traffic-control-awareness-training" },
      { t: "OSHA Driving Safety Training", u: "online-courses/osha-driving-safety-training" },
      { t: "OSHA Lead Awareness Training", u: "online-courses/lead-awareness-training-for-construction-industry" },
      { t: "OSHA Asbestos Awareness Training", u: "online-courses/asbestos-awareness-training" },
      { t: "OSHA Benzene Awareness Training", u: "online-courses/osha-benzene-awareness-training" },
      { t: "OSHA Hexavalent Chromium Awareness Training", u: "online-courses/osha-hexavalent-chromium-awareness-training" },
      { t: "OSHA Hexavalent Chromium Safety and Remediation Training", u: "online-courses/osha-hexavalent-chromium-safety-and-remediation-training" },
      { t: "OSHA Cadmium Awareness Training", u: "online-courses/osha-cadmium-awareness-training" },
      { t: "OSHA Silica Awareness Training", u: "online-courses/osha-silica-awareness-online-training" },
      { t: "OSHA Hot Work Safety for General Industry Training", u: "online-courses/osha-hot-work-safety-for-general-industry-training" },
      { t: "OSHA Noise Exposure and Hearing Conservation Training", u: "online-courses/osha-noise-exposure-and-hearing-conservation-training" },
      { t: "OSHA Spill Prevention and Response Safety Training", u: "online-courses/osha-spill-prevention-and-response-safety-training" },
      { t: "Cal/OSHA Spill Prevention and Response Safety Training", u: "online-courses/cal-osha-spill-prevention-and-response-safety-training" },
      { t: "OSHA Flammable and Combustible Liquids Awareness Training", u: "online-courses/osha-flammable-and-combustible-liquids-awareness-training" },
      { t: "OSHA Toxic and Hazardous Substances Safety Training", u: "online-courses/osha-toxic-and-hazardous-substances-safety-training" },
      { t: "Dust Disturbance and Mitigation Awareness Training", u: "online-courses/dust-disturbance-and-mitigation-awareness-training" },
      { t: "OSHA Ladder and Stairway Safety Training", u: "online-courses/osha-ladder-and-stairway-safety-training" },
      { t: "OSHA Respiratory Protection Safety Training", u: "online-courses/osha-respiratory-protection-safety-training" },
      { t: "OSHA SCBA Awareness and Safe Use Training", u: "online-courses/osha-scba-awareness-and-safe-use-training" },
      { t: "OSHA Personal Protective Equipment (PPE) Training", u: "online-courses/osha-personal-protective-equipment-training" },
      { t: "OSHA Full Body Harness Training", u: "online-courses/osha-full-body-harness-training" },
      { t: "Cal Wildfire Smoke Safety and Emergency Training", u: "online-courses/cal-wildfire-smoke-safety-and-emergency-training" },
      { t: "Wildfire Smoke Safety Awareness Training", u: "online-courses/wildfire-smoke-safety-awareness-training" },
      { t: "OSHA Cold Stress Awareness Training", u: "online-courses/osha-cold-stress-awareness-training" }
    ]},
    { name: "Radiation Series", courses: [
      { t: "NORM Worker Safety Training", u: "online-courses/norm-worker-safety-training" }
    ]},
    { name: "Competent Person Training", courses: [
      { t: "OSHA Competent Person for Excavation, Trenching, and Shoring Training", u: "online-courses/competent-person-for-excavation-trenching-and-shoring" },
      { t: "OSHA Competent Person for Confined Spaces Training", u: "online-courses/osha-competent-person-for-confined-spaces-training" },
      { t: "OSHA Scaffolding Erection and Inspection Training for Competent Person", u: "online-courses/osha-scaffolding-erection-and-inspection-training-for-competent-person" },
      { t: "OSHA Competent Person for Swing Stage (Suspended) Scaffold Training", u: "online-courses/osha-competent-person-for-swing-stage-suspended-scaffold-training" },
      { t: "OSHA Competent Person for Fall Protection Training", u: "online-courses/osha-competent-person-for-fall-protection-training-new" },
      { t: "OSHA Competent Person for Silica Training", u: "online-courses/osha-competent-person-for-silica-training-new" },
      { t: "OSHA Competent Person for Basic Rigging and Inspection Training", u: "online-courses/osha-competent-person-for-basic-rigging-and-inspection-training" }
    ]},
    { name: "Confined Space Training", courses: [
      { t: "OSHA Confined Space Awareness Training", u: "online-courses/confined-space-awareness-training-for-construction-industry" },
      { t: "OSHA Competent Person for Confined Spaces Training", u: "online-courses/osha-competent-person-for-confined-spaces-training" },
      { t: "OSHA Permit Required Confined Space Entry Training", u: "online-courses/osha-permit-required-confined-space-entry-training" },
      { t: "OSHA Confined Space Supervisor Training", u: "online-courses/osha-confined-space-supervisor-training" }
    ]},
    { name: "NFPA 70E Electrical & Arc Flash Safety", courses: [
      { t: "Electrical Safety Training (NFPA 70E 2024)", u: "online-courses/electrical-safety-training-nfpa-70e" },
      { t: "Lockout Tagout (LOTO) Training", u: "online-courses/osha-lockout-tagout-loto-training" },
      { t: "OSHA ANSI Lockout Tagout LOTO Certificate Training", u: "online-courses/osha-ansi-lockout-tagout-loto-certificate-training" },
      { t: "Arc Flash Safety Training (NFPA 70E 2024)", u: "online-courses/arc-flash-safety-training-nfpa-70e" },
      { t: "OSHA Ground Fault Protection /GFCI Safety Training (NFPA 70E 2024)", u: "online-courses/osha-ground-fault-protection-gfci-safety-training-nfpa-70e-2024" },
      { t: "Radiofrequency (RF) Safety and Hazard Awareness Training", u: "online-courses/radiofrequency-rf-safety-and-hazard-awareness-training" }
    ]},
    { name: "EPA Regulated Training", courses: [
      { t: "Qualified SWPPP Practitioner (QSP) Training", u: "online-courses/qualified-swppp-practitioner-qsp-training" },
      { t: "Qualified SWPPP Preparer Training", u: "online-courses/qualified-swppp-preparer-training" },
      { t: "RCRA Hazardous Waste Generator Training", u: "online-courses/rcra-hazwoper-waste-generator" },
      { t: "RCRA Hazardous Waste Generator Refresher Training", u: "online-courses/rcra-hazardous-waste-generator-refresher-training" },
      { t: "EPA Spill Prevention, Control, and Countermeasure (SPCC) Training", u: "online-courses/epa-spill-prevention-control-and-countermeasure-spcc-training" }
    ]},
    { name: "EM385-1-1 Training", courses: [
      { t: "EM 385-1-1 40-Hour Training", u: "online-courses/40-hour-em-385-1-1-training" },
      { t: "EM 385-1-1 24-Hour Training", u: "online-courses/em-385-1-1-24-hour-training" },
      { t: "EM 385-1-1 16-Hour Training for Workers", u: "online-courses/em-385-1-1-16-hour-training-for-workers" },
      { t: "EM 385-1-1 8-Hour Refresher Training for Site Safety and Health Officers (SSHOs)", u: "online-courses/em-385-1-1-8-hour-refresher-training-for-site-safety-and-health-officers-sshos" },
      { t: "EM 385-1-1 8-Hour Refresher Training For Workers", u: "online-courses/em-385-1-1-8-hour-refresher-training-for-workers" }
    ]},
    { name: "MSHA Part 46 Training", courses: [
      { t: "MSHA Part 46 New Miner Site Entry Training (Part 1)", u: "online-courses/msha-part-46-new-miner-site-entry-training-part-1" },
      { t: "MSHA Part 46 New Miner General Safety and Health Training (Part 2)", u: "online-courses/msha-part-46-new-miner-general-safety-and-health-training" },
      { t: "MSHA Part 46 8-Hour Refresher Training", u: "online-courses/msha-part-46-8-hour-refresher-training" }
    ]},
    { name: "HazCom and H2S Training", courses: [
      { t: "OSHA Hydrogen Sulfide Awareness Training", u: "online-courses/hydrogen-sulfide-awareness-training" },
      { t: "OSHA Hydrogen Sulfide (H2S) Training (International)", u: "online-courses/osha-hydrogen-sulfide-h2s-awareness-training-2-year" },
      { t: "Comprehensive Hydrogen Sulfide (H2S) Safety Training for the Oil & Gas Industry", u: "online-courses/comprehensive-h2s-training" },
      { t: "Hazard Communication (HazCom) with the Globally Harmonized System (GHS) Training", u: "online-courses/osha-hazard-communication-with-ghs" }
    ]},
    { name: "Ammonia Refrigeration Training", courses: [
      { t: "Ammonia Refrigeration Basics and Safety Awareness Training", u: "online-courses/ammonia-refrigeration-basics-and-safety-awareness-training" },
      { t: "Essentials of Ammonia Positive Displacement Compressors Training", u: "online-courses/essentials-of-ammonia-positive-displacement-compressors-training" },
      { t: "Design and Operation of Ammonia Evaporators, Condensers, and Controls Training", u: "online-courses/design-and-operation-of-ammonia-evaporators-condensers-and-controls-training" },
      { t: "Purging and Piping Strategies for Ammonia Refrigeration Systems Training", u: "online-courses/purging-and-piping-strategies-for-ammonia-refrigeration-systems-training" }
    ]},
    { name: "Mold Inspection & Remediation Certification", courses: [
      { t: "Mold Inspector Certification for Prevention, Remediation, and Removal Training", u: "online-courses/mold-inspector-certification-for-prevention-remediation-and-removal-training" },
      { t: "Mold Awareness, Prevention, and Remediation Training for Property Management Teams", u: "online-courses/mold-awareness-prevention-and-remediation-training-for-property-management-teams" },
      { t: "Mold Prevention and Remediation Awareness Training", u: "online-courses/mold-prevention-and-remediation-awareness-training" }
    ]},
    { name: "Hazmat & RCRA / DOT / IMDG / Lithium Battery Training", courses: [
      { t: "RCRA Hazardous Waste Generator Training", u: "online-courses/rcra-hazwoper-waste-generator" },
      { t: "RCRA Hazardous Waste Generator Refresher Training", u: "online-courses/rcra-hazardous-waste-generator-refresher-training" },
      { t: "Hazardous Waste Manifest Training", u: "online-courses/hazardous-waste-manifest-training" },
      { t: "10 Hour Advanced General Awareness Training", u: "online-courses/dot-hazmat-transportation-advanced-general-awareness-training" },
      { t: "4 Hour General Awareness Training", u: "online-courses/dot-hazmat-transportation-general-awareness-training" },
      { t: "DOT Hazmat Transportation: General Awareness with Function-Specific Training in Packaging & Labeling", u: "online-courses/dot-hazmat-transportation-general-awareness-with-function-specific-training-in-packaging-and-labeling" },
      { t: "DOT HAZMAT Transportation Supervisor Training for Highway", u: "online-courses/dot-hazmat-transportation-supervisor-training-for-highway" },
      { t: "DOT Training: The Hazmat Table", u: "online-courses/dot-hazmat-function-specific-training-the-hazmat-table" },
      { t: "DOT Training: Shipping Papers", u: "online-courses/dot-hazmat-function-specific-training-shipping-papers" },
      { t: "DOT Training: Packaging", u: "online-courses/dot-hazmat-function-specific-training-packaging" },
      { t: "DOT Training: Markings", u: "online-courses/dot-hazmat-function-specific-training-markings" },
      { t: "DOT Training: Labeling", u: "online-courses/dot-hazmat-function-specific-training-labeling" },
      { t: "DOT Training: Placarding", u: "online-courses/dot-hazmat-function-specific-training-placarding" },
      { t: "DOT Training: Security Awareness", u: "online-courses/dot-hazmat-function-specific-training-security-awareness" },
      { t: "DOT Hazmat Carrier Requirements: Highway", u: "online-courses/dot-hazmat-carrier-requirements-highway" },
      { t: "DOT Hazmat Carrier Requirements: Air/IATA", u: "online-courses/dot-hazmat-carrier-requirements-air-iata" },
      { t: "DOT Hazmat Carrier Requirements: Rail", u: "online-courses/dot-hazmat-carrier-requirements-rail" },
      { t: "DOT Hazmat Carrier Requirements: Vessel", u: "online-courses/dot-hazmat-carrier-requirements-vessel" },
      { t: "Shipping Lithium Batteries: Fully Regulated and Excepted Cells and Batteries Training", u: "online-courses/shipping-lithium-batteries-fully-regulated-and-excepted-cells-and-batteries" },
      { t: "Shipping Lithium Batteries: Fully Regulated Cells and Batteries", u: "online-courses/shipping-lithium-batteries-fully-regulated-cells-and-batteries" },
      { t: "Shipping Lithium Batteries: Excepted Cells and Batteries", u: "online-courses/shipping-lithium-batteries-excepted-cells-and-batteries" },
      { t: "Lithium Batteries Awareness Training", u: "online-courses/lithium-batteries-awareness-training" }
    ]},
    { name: "CDL Entry-Level Driver Training (ELDT)", courses: [
      { t: "CDL Entry Level Driver Training (ELDT) – Class A", u: "online-courses/cdl-entry-level-driver-training-eldt-class-a" },
      { t: "CDL Entry Level Driver Training (ELDT) - Class B", u: "online-courses/cdl-entry-level-driver-training-eldt-class-b-new" },
      { t: "CDL Entry Level Driver Training (ELDT) – Class B to Class A Upgrade", u: "online-courses/cdl-eldt-class-b-to-class-a-upgrade-new" },
      { t: "CDL Entry Level Driver Training (ELDT) - HAZMAT (H) Endorsement", u: "online-courses/cdl-entry-level-driver-training-eldt-hazmat-h-endorsement" },
      { t: "CDL Entry Level Driver Training (ELDT) - Hazmat and Tank Vehicle (X) Endorsement", u: "online-courses/cdl-entry-level-driver-training-eldt-hazmat-and-tank-vehicle-x-endorsement" },
      { t: "CDL Entry Level Driver Training (ELDT) - Tanker (N) Endorsement", u: "online-courses/cdl-entry-level-driver-training-eldt-tanker-n-endorsement" },
      { t: "CDL Entry Level Driver Training (ELDT) – Passenger (P) Endorsement", u: "online-courses/cdl-entry-level-driver-training-eldt-passenger-p-endorsement" },
      { t: "CDL Entry Level Driver Training (ELDT) – School Bus (S) Endorsement", u: "online-courses/cdl-entry-level-driver-training-eldt-school-bus-s-endorsement" }
    ]},
    { name: "Ergonomics & Injury Prevention Training", courses: [
      { t: "Ergonomics Safety Training", u: "online-courses/ergonomics-safety-training" },
      { t: "Back Safety and Injury Prevention Training", u: "online-courses/back-safety-and-injury-prevention-training" }
    ]},
    { name: "Healthcare & HIPAA Compliance Training", courses: [
      { t: "Drug and Alcohol Abuse Prevention Training for Construction Workers", u: "online-courses/drug-and-alcohol-abuse-prevention-training-for-construction-workers" },
      { t: "First Aid, CPR, and AED Safety Training", u: "online-courses/first-aid-cpr-and-aed-safety-awareness-training" },
      { t: "OSHA Bloodborne Pathogens Training", u: "online-courses/bloodborne-pathogens-training" },
      { t: "OSHA Toxic and Hazardous Substances Safety Training", u: "online-courses/osha-toxic-and-hazardous-substances-safety-training" },
      { t: "Pandemic Awareness, Preparedness, and Response Training", u: "online-courses/pandemic-awareness-preparedness-and-response-training" },
      { t: "HIPAA General Awareness Training", u: "online-courses/hipaa-general-awareness-training-new" }
    ]}
  ]
};
